"""
Quadratic Discriminant Analysis (QDA) - From Scratch Implementation

A classification technique that models each class with its own Gaussian distribution,
allowing for different covariance matrices per class. This leads to quadratic decision
boundaries, unlike LDA which assumes equal covariances and produces linear boundaries.

Key Concepts:
- Each class has its own mean and covariance matrix
- Decision boundaries are quadratic (elliptical, parabolic, or hyperbolic)
- More flexible than LDA but requires more parameters
- No dimensionality reduction (classification only)
"""

import numpy as np
from typing import Optional


class QuadraticDiscriminantAnalysis:
    """
    Quadratic Discriminant Analysis (QDA)

    QDA is a classifier with a quadratic decision boundary, generated by fitting
    class conditional densities to the data and using Bayes' rule.

    The model fits a Gaussian density to each class, where each class has its own
    covariance matrix. This is different from LDA which assumes all classes share
    the same covariance matrix.

    Mathematical Foundation:
    - Each class k has mean μ_k and covariance Σ_k
    - Decision function: δ_k(x) = -½ log|Σ_k| - ½(x-μ_k)ᵀΣ_k⁻¹(x-μ_k) + log π_k
    - Predict class with highest δ_k(x)

    Parameters
    ----------
    reg_param : float, default=1e-4
        Regularization parameter added to diagonal of covariance matrices
        Helps prevent singular matrices

    store_covariance : bool, default=False
        Whether to store covariance matrices (useful for analysis)

    tol : float, default=1e-4
        Threshold for numerical stability checks
    """

    def __init__(
        self,
        reg_param: float = 1e-4,
        store_covariance: bool = False,
        tol: float = 1e-4
    ):
        self.reg_param = reg_param
        self.store_covariance = store_covariance
        self.tol = tol

        # Fitted attributes
        self.classes_ = None
        self.priors_ = None
        self.means_ = None
        self.covariances_ = None
        self.n_features_in_ = None

    def fit(self, X: np.ndarray, y: np.ndarray):
        """
        Fit the Quadratic Discriminant Analysis model

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Training data

        y : array-like of shape (n_samples,)
            Target values (class labels)

        Returns
        -------
        self : object
            Fitted estimator
        """
        X = np.array(X)
        y = np.array(y)

        n_samples, n_features = X.shape
        self.n_features_in_ = n_features

        # Get unique classes
        self.classes_ = np.unique(y)
        n_classes = len(self.classes_)

        if n_classes < 2:
            raise ValueError("QDA requires at least 2 classes")

        # Compute class priors (proportion of each class)
        self.priors_ = np.array([np.sum(y == c) / n_samples for c in self.classes_])

        # Compute class means
        self.means_ = np.array([X[y == c].mean(axis=0) for c in self.classes_])

        # Compute class covariances (key difference from LDA!)
        self.covariances_ = []
        for c in self.classes_:
            X_c = X[y == c]
            n_c = len(X_c)

            # Center the class samples
            X_c_centered = X_c - X_c.mean(axis=0)

            # Compute covariance for this class
            cov = (X_c_centered.T @ X_c_centered) / (n_c - 1)

            # Add regularization to prevent singular matrices
            cov += self.reg_param * np.eye(n_features)

            self.covariances_.append(cov)

        self.covariances_ = np.array(self.covariances_)

        return self

    def _discriminant_function(self, X: np.ndarray) -> np.ndarray:
        """
        Compute discriminant function for each class

        For QDA, the discriminant function is:
        δ_k(x) = -½ log|Σ_k| - ½(x - μ_k)ᵀ Σ_k⁻¹ (x - μ_k) + log π_k

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Samples to evaluate

        Returns
        -------
        scores : array of shape (n_samples, n_classes)
            Discriminant scores for each class
        """
        n_samples = len(X)
        n_classes = len(self.classes_)
        scores = np.zeros((n_samples, n_classes))

        for idx, c in enumerate(self.classes_):
            # Get parameters for this class
            mean = self.means_[idx]
            cov = self.covariances_[idx]
            prior = self.priors_[idx]

            # Compute log determinant
            sign, logdet = np.linalg.slogdet(cov)
            if sign <= 0:
                raise ValueError(f"Covariance matrix for class {c} is not positive definite")

            # Compute inverse of covariance
            try:
                cov_inv = np.linalg.inv(cov)
            except np.linalg.LinAlgError:
                raise ValueError(f"Singular covariance matrix for class {c}")

            # Compute Mahalanobis distance for all samples
            diff = X - mean  # (n_samples, n_features)
            # Efficient computation: (X - μ)ᵀ Σ⁻¹ (X - μ)
            mahalanobis = np.sum(diff @ cov_inv * diff, axis=1)

            # Discriminant function
            scores[:, idx] = -0.5 * logdet - 0.5 * mahalanobis + np.log(prior)

        return scores

    def predict(self, X: np.ndarray) -> np.ndarray:
        """
        Predict class labels for samples

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Samples to predict

        Returns
        -------
        y_pred : array of shape (n_samples,)
            Predicted class labels
        """
        if self.means_ is None:
            raise ValueError("Model not fitted. Call fit() first.")

        X = np.array(X)

        # Compute discriminant scores
        scores = self._discriminant_function(X)

        # Predict class with highest score
        return self.classes_[np.argmax(scores, axis=1)]

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """
        Estimate probability of each class

        Uses softmax on discriminant scores to convert to probabilities

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Samples

        Returns
        -------
        proba : array of shape (n_samples, n_classes)
            Class probabilities
        """
        if self.means_ is None:
            raise ValueError("Model not fitted. Call fit() first.")

        X = np.array(X)

        # Compute discriminant scores
        scores = self._discriminant_function(X)

        # Convert to probabilities using softmax
        # Subtract max for numerical stability
        scores_exp = np.exp(scores - np.max(scores, axis=1, keepdims=True))
        proba = scores_exp / np.sum(scores_exp, axis=1, keepdims=True)

        return proba

    def predict_log_proba(self, X: np.ndarray) -> np.ndarray:
        """
        Estimate log probability of each class

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Samples

        Returns
        -------
        log_proba : array of shape (n_samples, n_classes)
            Log class probabilities
        """
        return np.log(self.predict_proba(X))

    def score(self, X: np.ndarray, y: np.ndarray) -> float:
        """
        Compute accuracy score

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Test samples

        y : array-like of shape (n_samples,)
            True labels

        Returns
        -------
        score : float
            Accuracy score
        """
        y_pred = self.predict(X)
        return np.mean(y_pred == y)

    def decision_function(self, X: np.ndarray) -> np.ndarray:
        """
        Compute decision function (discriminant scores)

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Samples

        Returns
        -------
        scores : array of shape (n_samples, n_classes)
            Decision function values
        """
        if self.means_ is None:
            raise ValueError("Model not fitted. Call fit() first.")

        return self._discriminant_function(X)


class RegularizedQDA(QuadraticDiscriminantAnalysis):
    """
    QDA with advanced regularization options

    Extends basic QDA with regularization towards:
    - Shared covariance (move towards LDA)
    - Diagonal covariance (independence assumption)

    Parameters
    ----------
    reg_param : float, default=1e-4
        Basic regularization added to diagonal

    shrinkage : float, default=None
        Shrinkage towards shared covariance (0 to 1)
        0 = QDA, 1 = LDA

    diagonal_shrinkage : float, default=None
        Shrinkage towards diagonal covariance (0 to 1)
        0 = full covariance, 1 = diagonal (Naive Bayes)

    store_covariance : bool, default=False
        Whether to store covariance matrices

    tol : float, default=1e-4
        Threshold for numerical stability
    """

    def __init__(
        self,
        reg_param: float = 1e-4,
        shrinkage: Optional[float] = None,
        diagonal_shrinkage: Optional[float] = None,
        store_covariance: bool = False,
        tol: float = 1e-4
    ):
        super().__init__(reg_param, store_covariance, tol)
        self.shrinkage = shrinkage
        self.diagonal_shrinkage = diagonal_shrinkage

    def fit(self, X: np.ndarray, y: np.ndarray):
        """
        Fit the Regularized QDA model

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Training data

        y : array-like of shape (n_samples,)
            Target values

        Returns
        -------
        self : object
            Fitted estimator
        """
        # First fit standard QDA
        super().fit(X, y)

        # Apply shrinkage towards shared covariance (move towards LDA)
        if self.shrinkage is not None:
            shrinkage = np.clip(self.shrinkage, 0, 1)

            # Compute shared covariance (as in LDA)
            X = np.array(X)
            y = np.array(y)
            n_samples, n_features = X.shape

            shared_cov = np.zeros((n_features, n_features))
            for idx, c in enumerate(self.classes_):
                X_c = X[y == c]
                X_c_centered = X_c - self.means_[idx]
                shared_cov += X_c_centered.T @ X_c_centered

            shared_cov /= (n_samples - len(self.classes_))
            shared_cov += self.reg_param * np.eye(n_features)

            # Shrink each class covariance towards shared covariance
            for idx in range(len(self.classes_)):
                self.covariances_[idx] = (
                    (1 - shrinkage) * self.covariances_[idx] +
                    shrinkage * shared_cov
                )

        # Apply diagonal shrinkage (move towards Naive Bayes)
        if self.diagonal_shrinkage is not None:
            diag_shrink = np.clip(self.diagonal_shrinkage, 0, 1)

            for idx in range(len(self.classes_)):
                cov = self.covariances_[idx]
                diag_cov = np.diag(np.diag(cov))

                self.covariances_[idx] = (
                    (1 - diag_shrink) * cov +
                    diag_shrink * diag_cov
                )

        return self
